### ISSUE TITLE
*may take a while*

### ISSUE THREAD

**Issue by DieselGaming** [felixrieseberg/windows-build-tools#168] opened 2019-01-08 19:53 UTC
I left my computer on for a day trying to install this, made no progress what so ever.
the cmd stayed the same way it did when i first used the installer.
any way i could hard install this?

**Comment by jacobq** [comment] 2019-01-08 23:05
What do you mean "hard install"? You can certainly download the MS build tools installer and python installer and run them. This package is mainly for convenience.

**Comment by DieselGaming** [comment] 2019-01-08 23:07
I read somewhere that you can go into the files and just basically paste in
these files and not have to use the stupid installer. I will look into it

**Comment by jacobq** [comment] 2019-01-09 15:19
I'm going to close this as it is very likely a duplicate of one of these:
#97, #147, #150 

Check out [the `nodejs/node-gyp` README.md](https://github.com/nodejs/node-gyp#on-windows) for more information about what is required to build native/OS-specific modules on Windows.

You can also peek at [`src/constants.ts`](https://github.com/felixrieseberg/windows-build-tools/blob/678b77cd7fcbc73e49a843d70c7f5524ba09cfc5/src/constants.ts#L38) to see the download URLs that this package uses.

**Closed by jacobq** 2019-01-09 15:19 UTC

**Comment by MichaelXF** [comment] 2019-02-01 22:40
23 days ago and this issue isn't resolved, nice work

**Comment by jacobq** [comment] 2019-02-02 00:15
@MichaelXF this issue is a duplicate. If you are having a problem not already tracked by an open issue please feel free to create a new one. If you have any new information that might be helpful for resolving a problem that would be welcome, as would a helpful PR.
