### ISSUE TITLE
Can't find Python executable "python" after installing

### ISSUE THREAD

**Issue by mikew** [felixrieseberg/windows-build-tools#56] opened 2017-04-23 08:09 UTC
node-gyp is failing because it can't find python. `windows-build-tools` did its thing and python is installed:

```
$ $(npm config get python)
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
$ npm --version
4.5.0
$ node --version
v7.9.0
```

Here's the output from `node-gyp`:

```
+ node_modules/.bin/electron-rebuild --arch x64 -f -p -w serialport -m electron-app
× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.9.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\mike\Work\dronefuse-client\node_modules\node-gyp\lib\configure.js:482:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\mike\Work\dronefuse-client\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\mike\Work\dronefuse-client\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mike\\Work\\dronefuse-client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.4.13" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=serialport" "--module_path=C:\\Users\\mike\\Work\\dronefuse-client\\electron-app\\node_modules\\serialport\\build\\Release" "--host=https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7"
gyp ERR! cwd C:\Users\mike\Work\dronefuse-client\electron-app\node_modules\serialport
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

**Comment by mikew** [comment] 2017-04-23 08:33
It's as if npm isn't even checking the value of `python` that is set, because this invocation works:

```bash
PATH="$(dirname $(npm config get python)):$PATH" node_modules/.bin/electron-rebuild --arch x64 -f -p -w serialport -m electron-app
```

**Comment by galkowskit** [comment] 2017-05-12 09:06
Same issue here.

**Comment by choucry13** [comment] 2017-05-17 13:04
+1

**Comment by garolion** [comment] 2017-05-26 22:54
solution: https://github.com/nfroidure/ttf2woff2/issues/28
npm install --global --production windows-build-tools

**Comment by felixrieseberg** [comment] 2017-06-08 01:42
Hm, seems like this is more with `electron-rebuild` than with `npm`. I assume the real solution here is to also ensure that `python` is globally accessible, which would require checking if it isn't already.

I'd gladly accept a PR for that, I'm not sure when I'll get to it.

**Comment by ArminMa** [comment] 2017-06-15 14:00
[https://github.com/felixrieseberg/windows-build-tools/issues/33](issues/33)

npm --add-python-to-path='true' --debug install --global windows-build-tools

**Comment by jeanru** [comment] 2017-09-06 08:52
npm config set python "c:\Python\27\python.exe"

**Comment by dougbacelar** [comment] 2017-10-19 14:27
@ArminMa solution solved my issue! Had to run the CLI as administrator.

**Comment by harrodevos** [comment] 2017-11-17 11:10
**@ArminMa**'s solution worked for me too!

I first had Python version 3.6 for Windows installed on a Windows Server 2016 machine. I used the windows executable installation.

This was required in order to install the web3 package.

But no matter how I set path and environment variables, during the npm install of web3 it kept complaining it couldn't find the python executable. Typing python in the command prompt worked fine.

I suspect it has to do with version/compatibility issues between web3 and python. After uninstalling the 3.6 version of python and installing 2.7 using the npm command ArminMa suggested it all works!

I did update my environment variables (PYTHON and PATH) to the 2.7 executable.

**Comment by thuyvtgl** [comment] 2017-12-06 15:32
Thank guys,
especially thank @ArminMa, you solved my issue.

**Comment by dhanabalcbt** [comment] 2017-12-30 12:22
thanks arima

**Comment by Philip-Nunoo** [comment] 2018-01-19 09:52
Thanks @ArminMa

**Comment by mapplics** [comment] 2018-01-26 09:44
thanks @AminMa you save my day!

**Comment by bibhuticoder** [comment] 2018-01-31 08:43
Installing python 2.* worked for me.

**Comment by hallss93** [comment] 2018-02-08 14:30
@garolion  obrigado. Estive com esse problema por um bom tempo. Consegui corrigir com isso! :1st_place_medal:

**Comment by SatishMHiremath** [comment] 2018-02-17 17:46
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules\@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @angular/cli@latest

angular client project folder path>npm install -g node-gyp

**Comment by walalm** [comment] 2018-06-05 16:18
Executing: `npm install --global --production windows-build-tools` and then
executing `npm rebuild` did the trick.

**Comment by hadnazzar** [comment] 2018-06-07 10:52
On windows: 
Run powershell as Administrator: 
and run
`npm --add-python-to-path='true' --debug install --global windows-build-tools`

**Comment by yuxinyue2016** [comment] 2018-06-12 10:23
谢谢你们的回答！管理员模式打开命令行工具并安装Windows工具真的解决了我的问题！thanks！

**Comment by brianHollingsworth** [comment] 2018-08-20 18:42
Thank you, @ArminMa!

**Comment by felixrieseberg** [comment] 2018-09-01 18:37
Thank you all, we're quite confident that most of these issues are now fixed 🙇

**Closed by felixrieseberg** 2018-09-01 18:37 UTC

**Comment by mscherer82** [comment] 2018-09-18 13:41
After running `npm --add-python-to-path='true' --debug install --global windows-build-tools` as administrator python has been added to my PATH when working as administrator. Shouldn't it be in the users PATH as well?

**Comment by yume117** [comment] 2018-09-20 14:46
Still getting this : 

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Julien.MARANTES\Documents\workspace\enfrasys\nbdtm-back\node_modules\unix-dgram
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by KrishnanSriram** [comment] 2018-09-23 23:02
I see python in my PATH variable as well as set up python as a environment variable. Tried everthing from above. It keeps failing with the same error. Not sure, how to fix it. Any help would be deeply appreciated

C:\Users\krish\Projects\ethereum\helloworldreact\client>echo %python%
**C:\Users\krish\.windows-build-tools\python27**

C:\Users\krish\Projects\ethereum\helloworldreact\client>**echo %PATH%**
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Go\bin;**C:\Users\krish\.windows-build-tools\python27;**C:\Users\krish\AppData\Local\Microsoft\WindowsApps;C:\Users\krish\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\krish\AppData\Roaming\npm;C:\Users\krish\AppData\Local\atom\bin;C:\Users\krish\AppData\Local\Microsoft\WindowsApps;C:\Users\krish\go\bin

C:\Users\krish\Projects\ethereum\helloworldreact\client\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\krish\.windows-build-tools\python27", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\krish\Projects\ethereum\helloworldreact\client\node_modules\keccak
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\krish\AppData\Roaming\npm-cache\_logs\2018-09-23T22_03_47_165Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

**Comment by Saibamen** [comment] 2018-09-27 19:45
What is your NPM and Node versions? (`node --version` and `npm --version`)
Did you installed *windows-build-tools* from CMD with admin access?
Installing windows-build-tools took some time. You must wait until
installation is really finished

pon., 24 wrz 2018 o 01:02 Krishnan Sriram <notifications@github.com>
napisał(a):

**Comment by Saibamen** [comment] 2018-09-27 19:46
What is your NPM and Node versions? (`node --version` and `npm --version`) Did you installed *windows-build-tools* from CMD with admin access? Installing windows-build-tools took some time. You must wait until installation is really finished

**Comment by KrishnanSriram** [comment] 2018-09-29 12:37
npm - 6.4.1
node - 10.11.0

**Comment by KrishnanSriram** [comment] 2018-09-29 13:09
I finally got it working with a very simple change. I re-installed Python for "All Users" insted of option "Only for me".

Updated Path variables for "python" & "path". Compilation worked well
Note: "truffle compile" does not work from "command prompt". But works well in "Powershell".

This was a minute work in LINUX & Mac, but a couple of days effort in Windows. When will Microsoft make Windows developer friendly????

**Comment by axeforeverjumo** [comment] 2018-10-12 08:58
> npm install --global --production windows-build-tools
Later installed this, you must specified the python2.7 link.

For that, you must search in your computer but must be locate in something like this:

> C:\Users\USERNAME\.windows-build-tools\python27\python.exe

So just execute this in your bash:

> npm config set python "C:\Users\USERNAME\.windows-build-tools\python27\python.exe"

**Comment by an-ivannikov** [comment] 2018-10-24 21:52
*Need to fix hands.*

```
PS G:\nodejs\test> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Alex\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Alex\AppData\Roaming\npm\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alex\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd G:\btc-test\rpc-miner
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
We're interested in that file. *Change to your windows user name*
`C:\Users\Alex\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js`
line number 32
`var python = gyp.opts.python || process.env.PYTHON || 'python2'`
change to your python location
`var python = 'C:\\Python\\27\\python.exe'`
```
function configure (gyp, argv, callback) {

  //var python = gyp.opts.python || process.env.PYTHON || 'python2'
  var python = 'C:\\Python\\27\\python.exe'
    , buildDir = path.resolve('build')
    , configNames = [ 'config.gypi', 'common.gypi' ]
    , configs = []
    , nodeDir
    , release = processRelease(argv, gyp, process.version, process.release)
```

**Comment by GibranLara** [comment] 2018-10-30 17:13
> in my case when I ran
> npm --add-python-to-path='true' --debug install --global windows-build-tools
> or
> npm install --global --production windows-build-tools
> it hags forever at this
> ---------- Visual Studio Build Tools ----------
> Still waiting for installer log file...
> ---------- Visual Studio Build Tools ----------
> Still waiting for installer log file...
> ------------------- Python --------------------
> 
> ---------- Visual Studio Build Tools ----------
> Successfully installed Visual Studio Build Tools
> ------------------- Python --------------------
> === Logging stopped: 8/17/2018 10:22:57 ===

Same, what you do?

**Comment by ramprasad2018** [comment] 2018-11-11 17:50
Hi All,
I am trying to call a C++ module from Node.js by using the ADDONS. The node-gyp configure is getting failed with the following Error. I am surpise why it searches for Python? I am not using Python at all.
C:\Ram\Projects\GraphQL\t\addon>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Software\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\software\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Ram\Projects\GraphQL\t\addon
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

C:\Ram\Projects\GraphQL\t\addon>
![capture](https://user-images.githubusercontent.com/43319298/48316347-4fad5600-e61d-11e8-8882-4113134f4ea3.JPG)

I also have attached the error.

Appreciate if any one can help.

**Comment by kamaatakh** [comment] 2018-12-05 02:11
> solution: [nfroidure/ttf2woff2#28](https://github.com/nfroidure/ttf2woff2/issues/28)
> npm install --global --production windows-build-tools


In my case npm wasn't finding the python.exe file when trying to run npm rebuild node-sass. After running "npm install --global --production windows-build-tools", I was able to run the command. 
Thanks @ArminMa 

"Error: not found: C:\Users\username\.windows-build-tools\python27\python.exe"

**Comment by Lingweifeng** [comment] 2018-12-10 08:07
> [https://github.com/felixrieseberg/windows-build-tools/issues/33](issues/33)
> 
> npm --add-python-to-path='true' --debug install --global windows-build-tools

 @ArminMa Thanks

**Comment by maikonmatheus** [comment] 2019-01-07 14:59
1 - Just uninstall Python from "C:\Users\username\.windows-build-tools\python27" 
2 - Reinstall running the msi install file, not command line. Link: https://www.python.org/downloads/release/python-2715/ 
2.1 - Check the option "Install for all users" and install on "C:\python27". 

Now node-gyp will find the Python normally

**Comment by Ju66ernaut** [comment] 2019-01-30 21:56
i encountered the same issue as @ramprasad2018 and with @refack and @maikonmatheus comments I was able to get it working by uninstalling Python 3.7 and then reinstalling/repairing Python 2.7 (which apparently came _with_ my python 3.7 download) and then running npm install again

**Comment by jefernandez89** [comment] 2019-02-20 04:07
> I finally got it working with a very simple change. I re-installed Python for "All Users" insted of option "Only for me".
> 
> Updated Path variables for "python" & "path". Compilation worked well
> Note: "truffle compile" does not work from "command prompt". But works well in "Powershell".
> 
> This was a minute work in LINUX & Mac, but a couple of days effort in Windows. When will Microsoft make Windows developer friendly????

As mentioned by @KrishnanSriram I was able tosolve this by running npm rebuild in "PowerShell" as administrator, it does not work on command prompt for me.

**Comment by webzmj530** [comment] 2019-03-26 09:00
为什么 Python 变量配过了 还是报can't find Python executable "python 2.7"? You can set the PYTHON env variable

**Comment by webzmj530** [comment] 2019-03-26 09:02
![image](https://user-images.githubusercontent.com/39976433/54984020-e7b64580-4fe8-11e9-8fa9-26babcd2d85b.png)

**Comment by thecodingaviator** [comment] 2019-05-20 20:37
@iamveritas How did you fix it?

**Comment by IIDarkKnightII** [comment] 2019-05-21 18:39
![image](https://user-images.githubusercontent.com/30504566/58121469-2c471180-7c25-11e9-8fd0-91521b3fcd12.png)


I've set npm config python path to point to 2.7 after running 

    npm install --global --production windows-build-tools


Here's config list after setting up python 2.7


![image](https://user-images.githubusercontent.com/30504566/58121750-bdb68380-7c25-11e9-85d7-b7423b0ab0b0.png)

**Comment by lukos** [comment] 2019-06-12 13:17
The problem is more fundamental than is mentioned here. A node module should not have a hard dependency on a build system like Python or MSBuild unless it can download one and install it without privileges locally or hold the user's hand.

This package is a help but it doesn't solve the problem because if, for example, you need to install it from an admin account, it gets installed in the admin account which makes it unusable for the non-admin users.

I had to delete where it was installed and then manually install the Python executable for all users, but the modify path didn't seem to do anything because it still didn't work. I then manually added the PYTHON environment variable before it would work.

Thanks for this package but it should either have some more instructions, a better default example in the docs (and shouldn't be needed if people didn't make ridiculous node package like node_gyp)!

**Comment by rashmimilan** [comment] 2019-09-20 11:14
> [https://github.com/felixrieseberg/windows-build-tools/issues/33](issues/33)
> 
> npm --add-python-to-path='true' --debug install --global windows-build-tools



Thank you so much!

**Comment by shatheesh123** [comment] 2019-10-02 09:24
Special thanks goes to @ArminMa ! works for me!

**Comment by Azkuu** [comment] 2019-11-22 14:41
> 1 - Just uninstall Python from "C:\Users\username\.windows-build-tools\python27"
> 2 - Reinstall running the msi install file, not command line. Link: https://www.python.org/downloads/release/python-2715/
> 2.1 - Check the option "Install for all users" and install on "C:\python27".
> 
> Now node-gyp will find the Python normally

it works halfway for me after I install python I need to install visual studio_BuildTools manually and select few other package too . now its working fine

**Comment by tayyabarif41** [comment] 2019-11-23 09:48
> solution: [nfroidure/ttf2woff2#28](https://github.com/nfroidure/ttf2woff2/issues/28)
> npm install --global --production windows-build-tools

it worked <3

**Comment by brianli-whitbread** [comment] 2019-12-11 14:08
> npm config set python "c:\Python\27\python.exe"

@jeanru, this command destroyed my development machine.

**Comment by tijazz** [comment] 2019-12-30 01:39
If you ever come across the above error on windows:
Run CMD as Administrator:
and run.
npm --add-python-to-path='true' --debug install --global windows-build-tools

that's all...

**Comment by B4Lee** [comment] 2020-01-07 16:24
I just solved the problem by reading this article

> https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

hope it helps !!

**Comment by ashutoshsoni** [comment] 2020-01-13 19:50
Thanks Satish.

**Comment by divya-kanak** [comment] 2020-01-18 05:35
Configuration: window 10, 64 bit, node v8.13.0, npm v6.4.1

Follow the below steps :

1. Restart the system

2. Open cmd by administrator

3. Delete C:\Users\user_name\.node-gyp

4. Delete %AppData%/npm

5. Delete %AppData%/npm-cache

6. Check out [node-gyp package][1]

7. npm install -g node-gyp

8. npm install --global --production windows-build-tools

9. node-gyp configure --python C:\Users\pcq158\.windows-build-tools\python27\python.exe

10. npm config set msvs_version 2017 --global

11. npm install

  [1]: https://github.com/nodejs/node-gyp

**Comment by krychuq1** [comment] 2020-01-21 11:49
I had to re-install python 2.7 and change  npm python config to: 

`npm config set python "c:\Python27\python.exe"`

**Comment by jawad-aziz-farhad** [comment] 2020-03-03 15:43
For Ubuntu 18.04.4 LTS
**npm --add-python-to-path='true' --debug install --global build-tools**

**Comment by felloz** [comment] 2020-09-15 18:27
> Hello @ramprasad2018, what you are seeing is a [bug in `node-gyp`](https://github.com/nodejs/node-gyp/pull/1534) where it fails to notify you that it can only work with python2.
> You can work around this until the fix is published, by running with:
> `node-gyp --python /path/to/python2.7`
> or setting:
> `npm config set python /path/to/executable/python2.7`
> Ref: https://github.com/nodejs/node-gyp#option-2

Thanks for the explanation, you deserve a beer sir.

**Comment by felloz** [comment] 2020-09-15 18:30
When i run `npm --add-python-to-path='true' --debug install --global windows-build-tools`

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lserrano\AppData\Roaming\npm-cache\_logs\2020-09-15T18_29_25_510Z-debug.log
```

Still having the issue

**Comment by iwasherefirst2** [comment] 2020-12-04 14:03
Its not working on Ubuntu:

```
npm --add-python-to-path='true' --debug install --global windows-build-tools
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for windows-build-tools@5.2.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adam/.npm/_logs/2020-12-04T14_01_39_361Z-debug.log
```

Any ideas how to fix it on Linux?

**Comment by jacobq** [comment] 2020-12-04 14:08
This module literally downloads and installs some Windows binaries (e.g. MS
Build Tools). It will not work on Linux (and is not needed in that case).
That is what this error message is trying to convey.

**Comment by iwasherefirst2** [comment] 2020-12-04 14:23
@jacobq whoups. Just realized that I was actually missing Python at all.lol..

**Comment by alvaropsouza** [comment] 2021-01-07 13:13
> [https://github.com/felixrieseberg/windows-build-tools/issues/33](issues/33)
> 
> npm --add-python-to-path='true' --debug install --global windows-build-tools

i think i love you. it worked man, thanks a lot!

**Comment by SergeyAP** [comment] 2021-01-18 12:24
> Its not working on Ubuntu:
> 
> ```
> npm --add-python-to-path='true' --debug install --global windows-build-tools
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for windows-build-tools@5.2.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm ERR! notsup Valid OS:    win32
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   linux
> npm ERR! notsup Actual Arch: x64
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/adam/.npm/_logs/2020-12-04T14_01_39_361Z-debug.log
> ```
> 
> Any ideas how to fix it on Linux?

How did you fix it? i have the same problem on macos

**Comment by jacobq** [comment] 2021-01-18 14:21
> > Its not working on Ubuntu: ...
> How did you fix it? i have the same problem on macos

As the name `windows-build-tools` is intended to suggest, this package is for installing Windows software needed to build native extensions/modules for NodeJS. It is completely unnecessary on Linux and MacOS. If you are intending to "cross-compile" Windows things on a non-Windows platform then I recommend using a virtualization layer (e.g. VirtualBox, Parallels, etc.) or cloud CI/CD offering (e.g. AppVeyor).

**Comment by sotickmars** [comment] 2021-02-17 08:31
run: npm cache clean --force
delete node_modules
delete packagelock.json and yarn.lock(if have)
run: npm install

**Comment by danieldanielecki** [comment] 2021-03-25 10:52
Installing `Python` from the [official source](https://www.python.org/downloads/windows/) fixed this issue on `Windows`...

**Comment by reuniware** [comment] 2021-05-27 15:17
> solution: [nfroidure/ttf2woff2#28](https://github.com/nfroidure/ttf2woff2/issues/28)
> npm install --global --production windows-build-tools

Thanks !!

**Comment by OxQ** [comment] 2021-05-31 14:13
Installing python (for Windows) using Microsoft Store has helped me.

**Comment by fabiovaz** [comment] 2021-07-02 19:14
after install windows build tools type
npm config set msvs_version 2017
saved me
